# Generated by Django 5.0.6 on 2024-06-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audio',
            old_name='uploaded_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='audio',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
