version: "3.8"
services:
  django_gunicorn:
    volumes:
      - ./project:/app
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    networks:
      - django_network

  postgres_db:
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sindikat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - django_network
    ports:
      - "5432:5432"

networks:
  django_network:
