services:
  sindikat-backend:
    container_name: sindikat-backend
    volumes:
      - media_data:/app/media
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      - postgres-db

  postgres-db:
    container_name: postgres-db
    image: postgres:latest
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: sindikat
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
