# Generated by Django 5.0.6 on 2024-07-22 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audios', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='file',
            field=models.FileField(max_length=255, upload_to='audios/'),
        ),
    ]
